version: '3.8'

services:
  
  cl_db:
    image: mongo
    container_name: cl_db
    restart: always
    volumes:
      - cl_db_data:/data/db
  
  cl_backend:
    container_name: cl_backend
    build: ./backend
    ports:
      - 4000:3000
    volumes:
      - ./backend:/usr/src/app
    restart: always
    environment:
      PORT: 3000
      DATABASE_PATH: mongodb://cl_db:27017
      DB_NAME: coderlogs
    depends_on:
      - cl_db
  
  cl_frontend:
    container_name: cl_frontend
    build: ./frontend
    ports:
      - 8001:8080
    volumes:
      - ./frontend:/usr/src/app
      - /usr/sr/app/node_modules
    stdin_open: true
    tty: true
    restart: always
    environment:
      # REACT_APP_API_URL: http://localhost:3000
      REACT_APP_API_URL:  https://www.api.coderlogs.com/
      REACT_APP_EN_MODE: DEVELOPMENT
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - cl_backend
    

volumes:
  cl_db_data: {}

